// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
      if (kIsWeb) {
        return web;
      }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Gtuhl8b62e627c4CmOp1Y-sgJW4bfw8',
    appId: '1:766260042781:android:80b32edc611558db67faf4',
    messagingSenderId: '766260042781',
    projectId: 'calyra-d143b',
    storageBucket: 'calyra-d143b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD87qGTevI6pOi7EwfQ6VNrhcoe_GltPag',
    appId: '1:766260042781:ios:391be90061ad931167faf4',
    messagingSenderId: '766260042781',
    projectId: 'calyra-d143b',
    storageBucket: 'calyra-d143b.firebasestorage.app',
    iosBundleId: 'com.example.calyra',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCK32BDTjtSreNvTIfDezMyKDwfk0kYzns",
    authDomain: "calyra-d143b.firebaseapp.com",
    projectId: "calyra-d143b",
    storageBucket: "calyra-d143b.firebasestorage.app",
    messagingSenderId: "766260042781",
    appId: "1:766260042781:web:dbd28e661390030067faf4",
    measurementId: "G-5P01QNP82L"
  );
}
