name: calyra
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Memperluas jangkauan kompatibilitas SDK

dependencies:
  flutter:
    sdk: flutter

  # --- Tambahan & Pembaruan Firebase ---
  # Pastikan versi ini sesuai, jalankan 'flutter pub outdated' untuk versi terbaru
  firebase_core: ^2.27.0 # Versi diperbarui untuk kompatibilitas
  firebase_auth: ^4.17.8 # Ditambahkan untuk Autentikasi
  cloud_firestore: ^4.15.8 # Ditambahkan untuk Database
  # ------------------------------------

  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.3 
  image_picker: ^1.2.0
  intl: ^0.20.2
  provider: ^6.1.5+1
  camera: ^0.11.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0 # Versi direkomendasikan untuk Flutter 3+

flutter:
  uses-material-design: true

  # --- Pendaftaran Aset ---
  # Bagian ini ditambahkan untuk mendaftarkan logo Anda
  assets:
    - assets/images/
  # ------------------------

  # --- Pendaftaran Font (sesuai SRS) ---
  # Tambahkan bagian ini jika Anda ingin menggunakan font Times New Roman
  # fonts:
  #   - family: Times New Roman
  #     fonts:
  #       - asset: assets/fonts/times_new_roman.ttf
  #       - asset: assets/fonts/times_new_roman_bold.ttf
  #         weight: 700
  # ---------------------------------------